# Neden Numpy?

In [1]:
a = [1,2,3,4]
b = [3,4,5,6]

In [2]:
ab = []
for i in range(len(a)):
    ab.append(a[i]*b[i])
ab    

[3, 8, 15, 24]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
a*b

array([ 3,  8, 15, 24])

In [5]:
import numpy as np
a = np.array([1,2,3,4,5])
a*5

array([ 5, 10, 15, 20, 25])

In [6]:
type(a)

numpy.ndarray

In [7]:
test = [1,2,3,4]
type(test)

list

In [15]:
a = np.array([1,2,3,4,"5"])
a  # integers are going to be converted string

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [16]:
a = np.array([1,2,3,4,5.5])
a # integers are going to be converted float

array([1. , 2. , 3. , 4. , 5.5])

In [18]:
a = np.array([1,2.2,3,4.6,"5"])
a # integers and floats are goint to be converted string

array(['1', '2.2', '3', '4.6', '5'], dtype='<U32')