# How to create numpy array

In [3]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [12]:
a = np.array([1,2,3,4,5])
print(a)
print(np.flip(a))

[1 2 3 4 5]
[5 4 3 2 1]


## We can give data type 

In [6]:
b = np.array([1,2,3,4,5], dtype = "int")
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [15]:
c = np.array([1,2,3,4,5], dtype = "float")
type(c[1])

numpy.float64

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros(10, dtype="str")
# integers zero -> 0, strings zero -> "", booleans zero -> false

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4),dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.full((3,4), 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [11]:
np.full((3,4), 3, dtype="str")

array([['3', '3', '3', '3'],
       ['3', '3', '3', '3'],
       ['3', '3', '3', '3']], dtype='<U1')

In [20]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

In [14]:
# 50 points between 1 and 2, default 50
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
#  ortalaması 10, standart sapması 4 olan 3 e 4 lük bir matris 
# (mean, std, size)
np.random.normal(10,4,(3,4))

array([[17.05447973, 10.75496925,  9.68505883, 14.21497673],
       [15.2997538 ,  6.24829314,  8.02230591, 10.71243001],
       [12.1181466 ,  4.78777965,  7.13654717,  8.44477564]])

In [23]:
np.random.randint(0,10,(3,3))

array([[2, 3, 1],
       [7, 5, 1],
       [8, 2, 8]])

In [4]:
a = np.random.randint(0,10,(3,3))
a

array([[4, 2, 8],
       [3, 4, 8],
       [5, 6, 7]])

In [19]:
d = {}
for _ in range(2000):
      val = np.random.randint(1,11)
      if val not in d:
            d[val] = 1
      else:
            d[val] += 1
d      

{1: 210,
 8: 192,
 10: 209,
 5: 206,
 9: 199,
 7: 207,
 3: 182,
 4: 191,
 2: 209,
 6: 195}

In [20]:
type(d)

dict

In [26]:
# creating identity(birim) matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])