# How to create numpy array

In [3]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [12]:
a = np.array([1,2,3,4,5])
print(a)
print(np.flip(a))

[1 2 3 4 5]
[5 4 3 2 1]


## We can give data type 

In [6]:
b = np.array([1,2,3,4,5], dtype = "int")
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [15]:
c = np.array([1,2,3,4,5], dtype = "float")
type(c[1])

numpy.float64

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros(10, dtype="str")
# integers zero -> 0, strings zero -> "", booleans zero -> false

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4),dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.full((3,4), 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [11]:
np.full((3,4), 3, dtype="str")

array([['3', '3', '3', '3'],
       ['3', '3', '3', '3'],
       ['3', '3', '3', '3']], dtype='<U1')

In [20]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### ortalaması 10, standart sapması 4 olan 3 e 4 lük bir matris 

In [22]:
np.random.normal(10,4,(3,4))

array([[ 9.91258153, 14.02350925, 12.80639656, 17.82617526],
       [11.81353737, 13.35470931, 10.40671669, 16.9102015 ],
       [ 6.54312811, 12.79984971, 13.02909809, 14.58185688]])

In [23]:
np.random.randint(0,10,(3,3))

array([[2, 3, 1],
       [7, 5, 1],
       [8, 2, 8]])

In [4]:
a = np.random.randint(0,10,(3,3))
a

array([[4, 2, 8],
       [3, 4, 8],
       [5, 6, 7]])

In [7]:
import numpy as np
x=np.array(["4.2"],dtype="int32") 
x  # cant be converted

ValueError: invalid literal for int() with base 10: '4.2'