# Özellikler

* **ndim** : _boyut sayisi_
* shape : boyut bilgisi
* size : toplam eleman sayisi
* dtype : array veri tipi

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=10)
a

array([3, 7, 6, 6, 8, 8, 3, 7, 5, 4])

In [3]:
b = np.random.randint(10)
b

0

In [4]:
a.ndim

1

In [6]:
a.shape

(10,)

In [7]:
a.size

10

In [8]:
a.dtype

dtype('int32')

In [ ]:
# np.random.randint(1,10, size = (3,3))

In [9]:
c = np.random.randint(1,10,(3,3))
c

array([[1, 3, 1],
       [2, 6, 2],
       [1, 9, 4]])

In [10]:
c.ndim

2

In [11]:
c.shape

(3, 3)

In [12]:
c.size

9

In [13]:
c.dtype

dtype('int32')

In [16]:
d = np.arange(1,10)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 