## Yeniden sekillendirme - Reshaping

In [1]:
import numpy as np

In [4]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = a.reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.ndim

2

In [11]:
b = b.reshape((1,9)) # 1 row, 9 column
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [2]:
import numpy as np
x = np.random.randint(1,10,10)
x

array([2, 3, 6, 6, 4, 7, 5, 8, 3, 5])

In [3]:
x.reshape((3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [5]:
x.reshape(-1,2) # -1, python calculate the number which should be separated  x = 5

array([[2, 3],
       [6, 6],
       [4, 7],
       [5, 8],
       [3, 5]])