## Array birlestirme (concatenation)

In [4]:
import numpy as np

In [5]:
a = [1,2,3]
b = [4,5,6]
a+b  # in normal python array

[1, 2, 3, 4, 5, 6]

In [7]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x+y # in nd array

array([5, 7, 9])

In [9]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
z = np.array([7,8,9])

In [24]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.concatenate([x,y,z]).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## iki boyut

In [26]:
t = np.array([
    [1,2,3],
    [4,5,6]
])
t

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.concatenate([t,t])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
np.concatenate([t,t], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
np.concatenate([t,t], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [22]:
x = np.array([1,2,3])
print(x)
print(x.shape)

[1 2 3]
(3,)


In [20]:
x = np.array([[1,2,3]])
print(x)
print(x.shape)

[[1 2 3]]
(1, 3)


In [18]:
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])

print(f"axis = 1 ; \n {np.concatenate((array_1, array_2), axis = 1)}")
print(f"axis = 1 ; \n {np.concatenate((array_1, array_2), axis = 0)}")

axis = 1 ; 
 [[1 2 3 0 0 0]
 [0 0 0 7 8 9]]
axis = 1 ; 
 [[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]


## Stack

In [35]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a.shape)
print(b.shape)

(4,)
(4,)


In [36]:
np.concatenate([a,b]) # difference of concatenate and stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a = np.array([[1,2,3,4]])
b = np.array([[5,6,7,8]])
print(a.shape)
print(b.shape)

(1, 4)
(1, 4)


In [44]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a.shape)
print(b.shape)

(4,)
(4,)


In [40]:
# stack creates a new dimension no need multi dimension

In [41]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
np.stack([a,b], axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])