## Array ayirma - Splitting

In [3]:
import numpy as np

In [3]:
x = np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [4]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [5]:
np.split(x,[2,4])

[array([1, 2]), array([ 3, 99]), array([99,  3,  2,  1])]

In [6]:
a,b,c = np.split(x,[3,5])

In [8]:
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [6]:
d = np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.vsplit(d,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [14]:
np.hsplit(d,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [16]:
up, down = np.vsplit(d,[2])

In [17]:
print(up)
print(down)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
