## array siralama - Sorting

In [2]:
import numpy as np

In [3]:
a = np.array([1,5,2,3,7,4])

In [4]:
a

array([1, 5, 2, 3, 7, 4])

In [5]:
np.sort(a) # this is not inplace

array([1, 2, 3, 4, 5, 7])

In [7]:
a.sort() # this is inplace like => a = np.sort(a)
a

array([1, 2, 3, 4, 5, 7])

In [5]:
b = np.random.normal(20,5,(3,3))
b

array([[13.34359609, 21.81513738, 19.50243281],
       [24.29919576, 25.67864949, 17.30324113],
       [18.27920605,  9.90399644, 28.63120737]])

In [6]:
np.sort(b)

array([[13.34359609, 19.50243281, 21.81513738],
       [17.30324113, 24.29919576, 25.67864949],
       [ 9.90399644, 18.27920605, 28.63120737]])

In [8]:
np.sort(b, axis = 1) # satirlara gore siralar

array([[13.34359609, 19.50243281, 21.81513738],
       [17.30324113, 24.29919576, 25.67864949],
       [ 9.90399644, 18.27920605, 28.63120737]])

In [9]:
np.sort(b, axis = 0) # sutunlara gore siralar

array([[13.34359609,  9.90399644, 17.30324113],
       [18.27920605, 21.81513738, 19.50243281],
       [24.29919576, 25.67864949, 28.63120737]])