## Index ile  elemanlara erismek

In [1]:
import numpy as np
a = np.random.randint(10,size = 10)
a

array([1, 2, 4, 6, 8, 3, 7, 4, 0, 1])

In [2]:
a[0]

1

In [3]:
a[-2]

0

In [4]:
a[0] = 100
a

array([100,   2,   4,   6,   8,   3,   7,   4,   0,   1])

In [5]:
b = np.random.randint(1,10,(3,3))
b

array([[8, 5, 3],
       [1, 7, 6],
       [3, 2, 3]])

In [6]:
b[0][1] = 99
b

array([[ 8, 99,  3],
       [ 1,  7,  6],
       [ 3,  2,  3]])

In [7]:
b[0][2] = 7.5  # numpy arrayleri fix type, sabitlenmiş tip, float bir deger ile degistirmeye calistigimiz zaman ondalikli kismi keser
b

array([[ 8, 99,  7],
       [ 1,  7,  6],
       [ 3,  2,  3]])

In [8]:
b[0,2] # b[0,2] = b[0][2]

7

In [9]:
c = np.arange(1,13).reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
c[1,1]

6

In [14]:
c[:,2]

array([ 3,  7, 11])

In [15]:
c[:][2]  # c[:,2] != c[:][2] be carefull

array([ 9, 10, 11, 12])

In [30]:
d = b*0.1

In [32]:
type(d[0][0])

numpy.float64