## Index ile  elemanlara erismek

In [9]:
import numpy as np
a = np.random.randint(10,size = 10)
a

array([8, 3, 2, 0, 3, 8, 7, 7, 4, 7])

In [4]:
a[0]

1

In [6]:
a[-2]

7

In [7]:
a[0] = 100
a

array([100,   7,   7,   6,   1,   8,   2,   4,   7,   1])

In [18]:
b = np.random.randint(1,10,(3,3))
b

array([[8, 8, 5],
       [7, 2, 8],
       [8, 1, 7]])

In [19]:
b[0][1] = 99
b

array([[ 8, 99,  5],
       [ 7,  2,  8],
       [ 8,  1,  7]])

In [20]:
b[0][2] = 7.5  # numpy arrayleri fix type, sabitlenmiş tip, float bir deger ile degistirmeye calistigimiz zaman ondalikli kismi keser
b

array([[ 8, 99,  7],
       [ 7,  2,  8],
       [ 8,  1,  7]])

In [30]:
d = b*0.1

In [32]:
type(d[0][0])

numpy.float64