## Slicing ile Elemanlara erismek

In [2]:
import numpy as np

In [3]:
a = np.arange(20,30)

In [5]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
a[0:3]

array([20, 21, 22])

In [7]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [9]:
a[0::2]

array([20, 22, 24, 26, 28])

In [10]:
a[0::3]

array([20, 23, 26, 29])

In [11]:
b = np.random.randint(1,10,(5,5))
b

array([[8, 4, 6, 8, 2],
       [5, 7, 6, 4, 4],
       [9, 2, 3, 1, 5],
       [9, 3, 6, 6, 6],
       [8, 4, 3, 7, 3]])

In [12]:
b[:,0] # 1.sutun

array([8, 5, 9, 9, 8])

In [13]:
b[:,1] # 2.sutun

array([4, 7, 2, 3, 4])

In [15]:
b[1,:] # 2.satir

array([5, 7, 6, 4, 4])

In [18]:
b[1][2]

6

In [19]:
b[1,2]

6

In [20]:
b[0:2,0:3]

array([[8, 4, 6],
       [5, 7, 6]])

In [21]:
a[::] # nasil bu sekilde hepsini aliyorsak

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
b[::,::] # seklinde de hepsini alabiliriz, gormek acisindan :: lari koyduk

array([[8, 4, 6, 8, 2],
       [5, 7, 6, 4, 4],
       [9, 2, 3, 1, 5],
       [9, 3, 6, 6, 6],
       [8, 4, 3, 7, 3]])

In [23]:
b[::,1:3]

array([[4, 6],
       [7, 6],
       [2, 3],
       [3, 6],
       [4, 3]])

In [24]:
b[0::2,1:3] # 2'ser atla dedik satirlar icin, sutunlar icinse 1.index ile 2.index'i al dedik

array([[4, 6],
       [2, 3],
       [4, 3]])