In [1]:
import numpy as np

In [11]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
v[1]

3

In [13]:
v[5]

15

In [14]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [16]:
indexesToSearch = [1,3,5]
v[indexesToSearch]

array([ 3,  9, 15])

In [20]:
b = np.arange(1,10).reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
row = np.array([0,1])
column = np.array([1,2])

In [22]:
b[row,column]

array([2, 6])

In [23]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
b[1,[1,2]]

array([5, 6])

In [26]:
b[0:,[1,2]]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [1]:
import numpy as np
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [2]:
idx = [1,5,10]
x[idx] = 99
x

array([ 1, 99,  3,  4,  5, 99,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
x[[2,7,5]] = 88
x

array([ 1, 99, 88,  4,  5, 88,  7, 88,  9, 10, 99, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
x[[6,12,18]]

array([100, 200, 300])

In [5]:
x[[6,12,18]] = [100,200,300]
x 

array([  1,  99,  88,   4,   5,  88, 100,  88,   9,  10,  99,  12, 200,
        14,  15,  16,  17,  18, 300,  20])