In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [3]:
v > 5

array([False, False, False, False, False])

In [4]:
v < 3

array([ True,  True, False, False, False])

In [12]:
v[v<3]


array([1, 2])

In [13]:
v[v != 3]

array([1, 2, 4, 5])

In [14]:
v[v == 3]

array([3])

In [15]:
v

array([1, 2, 3, 4, 5])

In [16]:
v*2

array([ 2,  4,  6,  8, 10])

In [17]:
v/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [3]:
import numpy as np
x = np.arange(1,21).reshape(4,5)

In [5]:
x > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
np.all(x>10)

False

In [8]:
np.all(x > -1)

True

In [9]:
np.all(x>10, axis = 1)

array([False, False,  True,  True])

In [10]:
np.all(x>10, axis = 0)

array([False, False, False, False, False])