In [1]:
import numpy as np

In [4]:
v = np.array([1,2,3,4,5,6])
v

array([1, 2, 3, 4, 5, 6])

In [5]:
v - 1

array([0, 1, 2, 3, 4, 5])

In [6]:
# ufunc

In [10]:
np.subtract(v,1) # v - 1

array([0, 1, 2, 3, 4, 5])

In [11]:
np.multiply(v,10) # v * 10

array([10, 20, 30, 40, 50, 60])

In [12]:
np.divide(v,5)

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [13]:
np.power(v,3)

array([  1,   8,  27,  64, 125, 216], dtype=int32)

In [14]:
np.mod(v,2) # v % 2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [15]:
np.absolute(np.array([-5])) 

array([5])

In [16]:
np.sin(360)

0.9589157234143065

In [17]:
np.cos(0)

1.0

In [18]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [20]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [25]:
x

array([1, 2, 3])

In [26]:
x.min()

1

In [27]:
x.max()

3

In [28]:
x.mean()

2.0

In [29]:
v.mean()

3.5

In [1]:
import numpy as np
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
np.sum(x)

210

In [8]:
x<5

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
np.sum(x[x<5])

10

In [9]:
filter = x < 5
np.sum(x[filter])

10

In [10]:
np.sum(x, axis = 0)

array([34, 38, 42, 46, 50])

In [11]:
np.sum(x,axis = 1)

array([15, 40, 65, 90])