# Eleman işlemleri

In [1]:
import numpy as np
import pandas as pd

In [7]:
s1 = np.random.randint(1,10,5)
s2 = np.random.randint(1,10,5)
s3 = np.random.randint(1,10,5)
print(s1)
print(s2)
print(s3)

[3 8 7 2 2]
[1 4 7 5 1]
[4 7 9 4 3]


In [8]:
dic = {"var1":s1, "var2":s2, "var3":s3}
dic

{'var1': array([3, 8, 7, 2, 2]),
 'var2': array([1, 4, 7, 5, 1]),
 'var3': array([4, 7, 9, 4, 3])}

In [9]:
df = pd.DataFrame(dic)
df

var1  var2  var3
0     3     1     4
1     8     4     7
2     7     7     9
3     2     5     4
4     2     1     3

In [10]:
df[0:1]

var1  var2  var3
0     3     1     4

In [11]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     3     1     4
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [13]:
df["c":"e"]

var1  var2  var3
c     7     7     9
d     2     5     4
e     2     1     3

In [14]:
df

var1  var2  var3
a     3     1     4
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [15]:
df.drop("a") # df.drop("a",axis = 0)

var1  var2  var3
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [17]:
df # a satır'ının kalıcı olarak silinmediğini görüyoruz, ya bi değişkene eşitleyecem ya da inplace = True kullanıcam

var1  var2  var3
a     3     1     4
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [21]:
df.drop("a",axis = 0, inplace = True) # kalıcı olarak siler

In [26]:
df

var1  var2  var3
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [27]:
df.drop(["c","d"])

var1  var2  var3
b     8     4     7
e     2     1     3

In [32]:
"b" in df

False

In [33]:
"var1" in df

True

In [35]:
df.index

Index(['b', 'c', 'd', 'e'], dtype='object')

In [36]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [40]:
for i in df.columns:
    print(i)

var1
var2
var3


In [41]:
df

var1  var2  var3
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [44]:
df["var1"]

b    8
c    7
d    2
e    2
Name: var1, dtype: int32

In [45]:
df["var4"] = df["var1"]*df["var2"]
df

var1  var2  var3  var4
b     8     4     7    32
c     7     7     9    49
d     2     5     4    10
e     2     1     3     2

In [47]:
df.drop("var4", axis = 1)

var1  var2  var3
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [48]:
df

var1  var2  var3  var4
b     8     4     7    32
c     7     7     9    49
d     2     5     4    10
e     2     1     3     2

In [49]:
df.drop("var4", axis = 1, inplace = True)

In [50]:
df

var1  var2  var3
b     8     4     7
c     7     7     9
d     2     5     4
e     2     1     3

In [51]:
l = ["var1","var2"]
df.drop(l,axis = 1)

var3
b     7
c     9
d     4
e     3

In [53]:
df.drop("c",axis = 0)

var1  var2  var3
b     8     4     7
d     2     5     4
e     2     1     3