# Çok Değişkenli Aykırı Gözlem Analizi

- Normalde 17 yaşında olmak aykırı değil. Normalde 3 kere evlenip boşanmakta aykırı değil. Ancak 17 yaşında 3 kere evlenip boşanmak aykırı bir değerdir. Genelin çok dışındadır.

## Local Outlier Factor

Gözlemleri bulundukları konumda yoğunluk tabanlı skorlayarak buna göre aykırı değer olabilecek değerleri tanımlayabilmemize imkan sağlıyor.

Bir noktanın local yoğunluğu bu noktanın komşuları ile karşılaştırılıyor. Eğer bir nokta komşularınının yoğunluğundan anlamlı şekilde düşük ise bu nokta komşularından daha seyrek bir bölgede bulunuyordur yorumu yapılabiliyor. Dolayısıyla burada bir komşuluk yapısı söz konusu. Bir değerin çevresi yoğun değilse demek ki bu değer aykırı değerdir şeklinde değerlendiriliyor.

In [1]:
import seaborn as sns
diamonds = sns.load_dataset('diamonds')
diamonds = diamonds.select_dtypes(include = ['float64', 'int64']) 
df = diamonds.copy()
df = df.dropna()
df.head()

carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43
1   0.21   59.8   61.0    326  3.89  3.84  2.31
2   0.23   56.9   65.0    327  4.05  4.07  2.31
3   0.29   62.4   58.0    334  4.20  4.23  2.63
4   0.31   63.3   58.0    335  4.34  4.35  2.75

In [2]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor

In [3]:
clf = LocalOutlierFactor(n_neighbors=20, contamination=0.1)

In [4]:
clf.fit_predict(df)

array([-1, -1, -1, ...,  1,  1,  1])

In [5]:
df_scores = clf.negative_outlier_factor_

In [14]:
df_scores

array([-1.58352526, -1.59732899, -1.62278873, ..., -1.06721815,
       -1.00809552, -1.00849038])

In [15]:
np.sort(df_scores)[0:20]

array([-8.60430658, -8.20889984, -5.86084355, -4.98415175, -4.81502092,
       -4.81502092, -4.61522833, -4.37081214, -4.29842288, -4.10492387,
       -4.0566648 , -4.01831733, -3.94882806, -3.82378797, -3.80135297,
       -3.75680919, -3.65947378, -3.59249261, -3.55564138, -3.47157375])

In [17]:
np.sort(df_scores)[13] # projeden projeye değişir tabi ama burada 13.index'deki değeri eşik değer kabul edelim.

-3.823787967755565

In [22]:
threshold_value = np.sort(df_scores)[13]

## Silme

In [28]:
not_outliers_df = df_scores > threshold_value
not_outliers_df

array([ True,  True,  True, ...,  True,  True,  True])

In [31]:
clean_df = df[not_outliers_df]
clean_df # aykırı olmayan değerler

carat  depth  table  price     x     y     z
0       0.23   61.5   55.0    326  3.95  3.98  2.43
1       0.21   59.8   61.0    326  3.89  3.84  2.31
2       0.23   56.9   65.0    327  4.05  4.07  2.31
3       0.29   62.4   58.0    334  4.20  4.23  2.63
4       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53926 rows x 7 columns]

In [32]:
outliers_df = df[df_scores < threshold_value]
outliers_df # aykırı değerler

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09